services:
  app:
    image: app:latest
    restart: always
    build: .
    depends_on:
      - database
    links:
      - database
    ports:
      - ${COMPOSE_APP_PORT:-3000}:3000
    environment:
      DATABASE_HOST: ${DATABASE_HOST:-database}
      DATABASE_PORT: ${DATABASE_PORT:-5432}
      DATABASE_USER: ${DATABASE_USER:-postgres}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      DATABASE_NAME: ${DATABASE_NAME:-postgres}
      DATABASE_SSL: ${DATABASE_SSL:-false}
      VITE_HOST_URL: ${VITE_HOST_URL:-http://localhost:3000}

  database:
    image: postgres:16-alpine
    restart: always
    ports:
      - ${DATABASE_PORT:-5432}:5432
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_DATABASE: ${DATABASE_NAME:-postgres}
    volumes:
      - database:/var/lib/postgresql/data

  backup:
    image: offen/docker-volume-backup:v2
    restart: always
    depends_on:
      - database
    links:
      - database
    environment:
      BACKUP_LATEST_SYMLINK: backup-latest.tar.gz
      BACKUP_CRON_EXPRESSION: 0 0 * * *
      BACKUP_RETENTION_DAYS: 14
    volumes:
      - database:/backup:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${COMPOSE_DATABASE_BACKUP_PATH:-$HOME/backup}/${COMPOSE_PROJECT_NAME}:/archive
    profiles:
      - production

volumes:
  database:
